/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 /Users/adrian/Downloads/low_poly_home_1/scene.gltf --transform 
Files: /Users/adrian/Downloads/low_poly_home_1/scene.gltf [4KB] > /Users/adrian/Projects/house-builder-prototype/scene-transformed.glb [29.86KB] (-646%)
Author: Digital screen official (https://sketchfab.com/ck212575)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-home-1-750826b0bdab4d97a32ae1680a5e7e02
Title: low poly home 1
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ProjectTwo(props) {
  const { nodes, materials } = useGLTF("/project-two-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/project-two-transformed.glb");
