/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 /Users/adrian/Downloads/morden_wood_cabin_-_small_wood_house/scene.gltf --transform 
Files: /Users/adrian/Downloads/morden_wood_cabin_-_small_wood_house/scene.gltf [2.81MB] > /Users/adrian/Projects/house-builder-prototype/scene-transformed.glb [6.26MB] (-123%)
Author: MarMel-Bali (https://sketchfab.com/MarMel-Bali)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/morden-wood-cabin-small-wood-house-2b4bee30275343369957045a41dbe781
Title: Morden Wood Cabin - Small Wood House
*/

import { useGLTF } from "@react-three/drei";
import { useRef, useEffect, useState } from "react";

export function ProjectTwo(props) {
  const { nodes, materials } = useGLTF("/project-second-transformed.glb");

  const doorRef = useRef();
  const [doorOriginalColor, setDoorOriginalColor] = useState(null);

  const windowRef = useRef();
  const [windowOriginalColor, setWindowOriginalColor] = useState(null);

  const wallsRef = useRef();
  const [wallsOriginalColor, setWallsOriginalColor] = useState(null);

  useEffect(() => {
    if (doorRef.current) {
      setDoorOriginalColor(doorRef.current.material.color.clone());
    }

    if (windowRef.current) {
      setWindowOriginalColor(windowRef.current.material.color.clone());
    }

    if (wallsRef.current) {
      setWallsOriginalColor(wallsRef.current.material.color.clone());
    }

    if (props.controls.roofColor !== "Standard") {
      alert("Roof color is not supported on this model");
      props.setControls({ roofColor: "Standard" });
    }
  }, [
    props.controls.Model,
    props.controls.roofColor,
    doorRef.current,
    windowRef.current,
    wallsRef.current,
  ]);

  return (
    <group {...props} dispose={null}>
      {/* external floor */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh1_Pigmented_Concrete_0.geometry}
        material={materials.Pigmented_Concrete}
        scale={0.004}
      />
      {/* internal floor */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh1_Douglas_Fir_Staggered1_0.geometry}
        material={materials.Douglas_Fir_Staggered1}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh1_Inverna_Terrazzo_0.geometry}
        material={materials.Inverna_Terrazzo}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh2_FrontColor_0.geometry}
        material={materials.PaletteMaterial001}
        scale={0.004}
      />
      {/* main walls */}
      <mesh
        ref={wallsRef}
        castShadow
        receiveShadow
        geometry={nodes.Mesh2_Western_Red_Cedar_Stack_0.geometry}
        material={materials.Western_Red_Cedar_Stack}
        scale={0.004}
      >
        <primitive
          attach="material"
          object={materials.Western_Red_Cedar_Stack}
          color={
            props.controls.wallsColor === "Standard"
              ? wallsOriginalColor
              : props.controls.wallsColor
          }
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh2_Ash_0.geometry}
        material={materials.material}
        scale={0.004}
      />
      {/* secondary walls */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh2_Douglas_Fir_Staggered_0.geometry}
        material={materials.Douglas_Fir_Staggered}
        scale={0.004}
      />
      {/* windows */}
      <mesh
        ref={windowRef}
        castShadow
        receiveShadow
        geometry={nodes.Mesh4_Steel_Brushed_Stainless_0.geometry}
        material={materials.brushed_aluminium1}
        scale={0.004}
      >
        <primitive
          attach="material"
          object={materials.brushed_aluminium1}
          color={
            props.controls.windowColor === "Standard"
              ? windowOriginalColor
              : props.controls.windowColor
          }
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh8_Translucent_Glass_Gray_0.geometry}
        material={materials.PaletteMaterial002}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Mesh29_Corrugated_Dark_Matte_Powder_Coated_Metal_0.geometry
        }
        material={materials.Corrugated_Dark_Matte_Powder_Coated_Metal}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh31__Translucent_Glass_Gray_1_0.geometry}
        material={materials.PaletteMaterial003}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh43_brushed_aluminium1_0.geometry}
        material={materials.brushed_aluminium1}
        scale={0.004}
      />
      {/* door */}
      <mesh
        ref={doorRef}
        castShadow
        receiveShadow
        geometry={
          nodes.Mesh83_M_22_raw_wood_oak_light_PBR_texture_seamless_0.geometry
        }
        material={materials.M_22_raw_wood_oak_light_PBR_texture_seamless}
        scale={0.004}
      >
        <primitive
          attach="material"
          object={materials.M_22_raw_wood_oak_light_PBR_texture_seamless}
          color={
            props.controls.doorColor === "Standard"
              ? doorOriginalColor
              : props.controls.doorColor
          }
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh86_______Vicky______50_0.geometry}
        material={materials.Vicky______50}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh86_______Vicky______10_0.geometry}
        material={materials.Vicky______10}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh91_Generic_3_0.geometry}
        material={materials.Generic_3}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh94_Knotted_Timber_0.geometry}
        material={materials.Knotted_Timber}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh94_Knotted_Timber1_0.geometry}
        material={materials.Knotted_Timber1}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh118_Metal_Corrugated_Shiny_0.geometry}
        material={materials.Metal_Corrugated_Shiny}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh125_Granite_Dark_Gray_0.geometry}
        material={materials.Granite_Dark_Gray}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh148_Grizzly_Adams_0.geometry}
        material={materials.Grizzly_Adams}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh154_Knotted_Timber2_0.geometry}
        material={materials.Knotted_Timber2}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh155_Knotted_Timber3_0.geometry}
        material={materials.Knotted_Timber3}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh156_Knotted_Timber4_0.geometry}
        material={materials.Knotted_Timber4}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh158_Knotted_Timber5_0.geometry}
        material={materials.Knotted_Timber5}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh159_Knotted_Timber6_0.geometry}
        material={materials.Knotted_Timber6}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh168_Wood_1_0.geometry}
        material={materials.Wood_1}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh213__WALNUT1_0.geometry}
        material={materials.WALNUT1}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh213__WALNUT1_1_0.geometry}
        material={materials.WALNUT1_1}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh240_Lavatrice_0.geometry}
        material={materials.Lavatrice}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh240_Colore_lavatrice_0.geometry}
        material={materials.Colore_lavatrice}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh260_Kitchen_0.geometry}
        material={materials.Kitchen}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh266_Mirror_01_0.geometry}
        material={materials.Mirror_01}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Mesh279_M_62_wood_ceramic_tile_texture_seamless_0.geometry
        }
        material={materials.M_62_wood_ceramic_tile_texture_seamless}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh301_a509ed0cd8d0_original_0.geometry}
        material={materials.a509ed0cd8d0_original}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh328_Metal_Silver_0.geometry}
        material={materials.Metal_Silver}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh330_llum_emissive_0.geometry}
        material={materials.PaletteMaterial004}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh346_pot_beige_0.geometry}
        material={materials.pot_beige}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh349_blad1_0.geometry}
        material={materials.blad1}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh352_blad2_0.geometry}
        material={materials.blad2}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh353_Screenshot_3_0.geometry}
        material={materials.Screenshot_3}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh356_Persian_Rug_blue_0.geometry}
        material={materials.Persian_Rug_blue}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh437_Carpet_Plush_Forest_0.geometry}
        material={materials.Carpet_Plush_Forest}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh438_Carpet_Loop_Pattern_0.geometry}
        material={materials.Carpet_Loop_Pattern}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh440_Oak_0.geometry}
        material={materials.material_56}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh442_Sofa_Midas_Estofado_Leather_0.geometry}
        material={materials.Sofa_Midas_Estofado_Leather}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh489_VP_Ficus_Elastica_bark1_0.geometry}
        material={materials.VP_Ficus_Elastica_bark1}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh490_VP_ficus_elastica_leaf_1_0.geometry}
        material={materials.VP_ficus_elastica_leaf_1}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh491_VP_ficus_elastica_leaf_2_0.geometry}
        material={materials.VP_ficus_elastica_leaf_2}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh492_VP_ficus_elastica_leaf_3_0.geometry}
        material={materials.VP_ficus_elastica_leaf_3}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh493_VP_Ficus_Elastica_cone1_0.geometry}
        material={materials.VP_Ficus_Elastica_cone1}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh495_VP_pot_wood_shavings1_0.geometry}
        material={materials.VP_pot_wood_shavings1}
        scale={0.004}
      />
    </group>
  );
}

useGLTF.preload("/project-second-transformed.glb");
